export const RACE_ADD = "[RACE] add";
export const RACE_DELETE = "[RACE] delete";
export const RACE_UPDATE = "[RACE] update";
export const RACE_DELETE_BY_SESSION_ID = "[RACE] delete by session id";

export const RACE_CURCUIT = [
  "Autodromo Nazionale Monza",
  "Bernese Alps",
  "Bathurst",
  "Brands Hatch",
  "Circuit de Catalunya",
  "Circuit of the Americas",
  "Daytona International Speedway",
  "Dubai Circuit",
  "Hockenheim Ring",
  "Homestead-Miami Speedway",
  "Indianapolis Motor Speedway",
  "Le Mans Circuit de la Sarthe",
  "Lime Rock",
  "Long Beach",
  "Maple Valley Raceway",
  "Mazda Raceway Laguna Seca",
  "Mount Panorama Circuit",
  "Mugello Autodromo Internazionale",
  "Nürburgring",
  "Prague",
  "Rio de Janeiro",
  "Road America",
  "Road Atlanta",
  "Sebring International Raceway",
  "Silverstone Racing Circuit",
  "Sonoma Raceway",
  "Spa-Francorchamps",
  "Suzuka Circuit",
  "Test Track Airfield",
  "Top Gear Test Track",
  "Virginia International Raceway",
  "Watkins Glen",
  "Yas Marina Circuit",
];
